apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: k8s-demo
    tier: frontend
spec:
  selector:
    app: k8s-demo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
